In [1]:
import numpy as np

a = np.random.randn(5)

In [2]:
print(a)

[ 1.02728568  1.32467915 -0.00983693  1.45336042 -0.41313422]


In [3]:
print(a.shape)

(5,)


In [5]:
print(a.T)

[ 1.02728568  1.32467915 -0.00983693  1.45336042 -0.41313422]


In [6]:
print(np.dot(a,a.T))


#上述操作会生成秩为1的向量，容易产生意想不到的错误

5.09312387362472


In [7]:
a = np.random.randn(5,1)
print(a)

[[ 0.27394051]
 [-0.73963243]
 [-1.6601246 ]
 [ 1.83584358]
 [-1.16863966]]


In [8]:
print(a.T)

[[ 0.27394051 -0.73963243 -1.6601246   1.83584358 -1.16863966]]


In [9]:
print(np.dot(a,a.T))

[[ 0.0750434  -0.20261529 -0.45477538  0.50291193 -0.32013775]
 [-0.20261529  0.54705613  1.22788199 -1.35784944  0.86436378]
 [-0.45477538  1.22788199  2.7560137  -3.04772909  1.94008744]
 [ 0.50291193 -1.35784944 -3.04772909  3.37032164 -2.1454396 ]
 [-0.32013775  0.86436378  1.94008744 -2.1454396   1.36571864]]
